networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - server
      - front
    networks:
      - dev
    

  server:
    build:
      context: ./server
    networks:
      - dev

  front:
    build:
      context: ./front
    networks:
      - dev

  pg:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME_STAGE}
      - POSTGRES_USER=${DB_USER_STAGE}
      - POSTGRES_PASSWORD=${DB_PASS_STAGE}
    ports:
      - "${DB_PORT_STAGE}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_STAGE}"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - dev
