"""added admission number to sailor data

Revision ID: 6aa47ece8e7c
Revises: 2cdf2fb2cc45
Create Date: 2025-05-29 15:44:12.663932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa47ece8e7c'
down_revision: Union[str, None] = '2cdf2fb2cc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sailor_create_requests', sa.Column('admission', sa.Integer(), nullable=False, comment='Номер набора в школу'))
    op.add_column('sailors', sa.Column('admission', sa.Integer(), nullable=False, comment='Номер набора в школу'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sailors', 'admission')
    op.drop_column('sailor_create_requests', 'admission')
    # ### end Alembic commands ###
