"""requirements changes

Revision ID: 0c08d42f8bc8
Revises: f1b0d2b39811
Create Date: 2025-06-15 14:47:37.534509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c08d42f8bc8'
down_revision: Union[str, None] = 'f1b0d2b39811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sailor_create_requests', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='Ссылка на фото моряка')
    op.alter_column('sailors', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='Ссылка на фото моряка')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sailors', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='Ссылка на фото моряка')
    op.alter_column('sailor_create_requests', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='Ссылка на фото моряка')
    # ### end Alembic commands ###
