"""initial migration

Revision ID: 2cdf2fb2cc45
Revises: 
Create Date: 2025-05-29 15:22:02.389630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdf2fb2cc45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='ФИО отправителя'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Почта отправителя'),
    sa.Column('message', sa.String(length=5000), nullable=False),
    sa.Column('additional_information', sa.String(length=500), nullable=True, comment='Дополнительные сведения от пользователя, например для связи(телефон, telegram, vk и т.д.)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False, comment='Дата создания обращения'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('sailor_create_requests',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор заявки'),
    sa.Column('user_fullname', sa.String(length=100), nullable=False, comment='ФИО пользователя, подавшего заявку'),
    sa.Column('user_email', sa.String(length=255), nullable=False, comment='Email пользователя'),
    sa.Column('additional_information', sa.String(length=500), nullable=True, comment='Дополнительные сведения от пользователя, например для связи(телефон, telegram, vk и т.д.)'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False, comment='Статус заявки'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False, comment='Дата создания заявки'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата последнего обновления'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='Имя моряка'),
    sa.Column('surname', sa.String(length=30), nullable=False, comment='Фамилия моряка'),
    sa.Column('patronymic', sa.String(length=30), nullable=False, comment='Отчество моряка'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='Дата рождения (ГГГГ-ММ-ДД)'),
    sa.Column('death_date', sa.Date(), nullable=True, comment='Дата смерти (ГГГГ-ММ-ДД), если известна'),
    sa.Column('photo_url', sa.String(length=500), nullable=True, comment='Ссылка на фото моряка'),
    sa.Column('biography', sa.String(length=10000), nullable=True, comment='Биография'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sailor_create_requests_id'), 'sailor_create_requests', ['id'], unique=False)
    op.create_table('sailors',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор биографии'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False, comment='Дата создания'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='Имя моряка'),
    sa.Column('surname', sa.String(length=30), nullable=False, comment='Фамилия моряка'),
    sa.Column('patronymic', sa.String(length=30), nullable=False, comment='Отчество моряка'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='Дата рождения (ГГГГ-ММ-ДД)'),
    sa.Column('death_date', sa.Date(), nullable=True, comment='Дата смерти (ГГГГ-ММ-ДД), если известна'),
    sa.Column('photo_url', sa.String(length=500), nullable=True, comment='Ссылка на фото моряка'),
    sa.Column('biography', sa.String(length=10000), nullable=True, comment='Биография'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sailors_id'), 'sailors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sailors_id'), table_name='sailors')
    op.drop_table('sailors')
    op.drop_index(op.f('ix_sailor_create_requests_id'), table_name='sailor_create_requests')
    op.drop_table('sailor_create_requests')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
