"""reformatted dates in sailors table

Revision ID: f1b0d2b39811
Revises: 6aa47ece8e7c
Create Date: 2025-06-13 03:22:10.761875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1b0d2b39811'
down_revision: Union[str, None] = '6aa47ece8e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sailor_create_requests', sa.Column('birth_day', sa.Integer(), nullable=True, comment='День рождения(опционально)'))
    op.add_column('sailor_create_requests', sa.Column('birth_month', sa.Integer(), nullable=True, comment='Месяц рождения(опционально)'))
    op.add_column('sailor_create_requests', sa.Column('birth_year', sa.Integer(), nullable=True, comment='Год рождения(опционально)'))
    op.add_column('sailor_create_requests', sa.Column('death_day', sa.Integer(), nullable=True, comment='День смерти(опционально)'))
    op.add_column('sailor_create_requests', sa.Column('death_month', sa.Integer(), nullable=True, comment='Месяц смерти(опционально)'))
    op.add_column('sailor_create_requests', sa.Column('death_year', sa.Integer(), nullable=True, comment='Год смерти(опционально)'))
    op.drop_column('sailor_create_requests', 'birth_date')
    op.drop_column('sailor_create_requests', 'updated_at')
    op.drop_column('sailor_create_requests', 'death_date')
    op.add_column('sailors', sa.Column('birth_day', sa.Integer(), nullable=True, comment='День рождения(опционально)'))
    op.add_column('sailors', sa.Column('birth_month', sa.Integer(), nullable=True, comment='Месяц рождения(опционально)'))
    op.add_column('sailors', sa.Column('birth_year', sa.Integer(), nullable=True, comment='Год рождения(опционально)'))
    op.add_column('sailors', sa.Column('death_day', sa.Integer(), nullable=True, comment='День смерти(опционально)'))
    op.add_column('sailors', sa.Column('death_month', sa.Integer(), nullable=True, comment='Месяц смерти(опционально)'))
    op.add_column('sailors', sa.Column('death_year', sa.Integer(), nullable=True, comment='Год смерти(опционально)'))
    op.alter_column('sailors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата добавления биографии',
               existing_comment='Дата создания',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, CURRENT_TIMESTAMP)"))
    op.drop_column('sailors', 'birth_date')
    op.drop_column('sailors', 'death_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sailors', sa.Column('death_date', sa.DATE(), autoincrement=False, nullable=True, comment='Дата смерти (ГГГГ-ММ-ДД), если известна'))
    op.add_column('sailors', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False, comment='Дата рождения (ГГГГ-ММ-ДД)'))
    op.alter_column('sailors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата создания',
               existing_comment='Дата добавления биографии',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, CURRENT_TIMESTAMP)"))
    op.drop_column('sailors', 'death_year')
    op.drop_column('sailors', 'death_month')
    op.drop_column('sailors', 'death_day')
    op.drop_column('sailors', 'birth_year')
    op.drop_column('sailors', 'birth_month')
    op.drop_column('sailors', 'birth_day')
    op.add_column('sailor_create_requests', sa.Column('death_date', sa.DATE(), autoincrement=False, nullable=True, comment='Дата смерти (ГГГГ-ММ-ДД), если известна'))
    op.add_column('sailor_create_requests', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата последнего обновления'))
    op.add_column('sailor_create_requests', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False, comment='Дата рождения (ГГГГ-ММ-ДД)'))
    op.drop_column('sailor_create_requests', 'death_year')
    op.drop_column('sailor_create_requests', 'death_month')
    op.drop_column('sailor_create_requests', 'death_day')
    op.drop_column('sailor_create_requests', 'birth_year')
    op.drop_column('sailor_create_requests', 'birth_month')
    op.drop_column('sailor_create_requests', 'birth_day')
    # ### end Alembic commands ###
